# Generated by Django 2.2.7 on 2020-07-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tables',
            new_name='Table',
        ),
    ]
