# Generated by Django 2.2.7 on 2020-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200511_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Summery',
            field=models.TextField(blank=True, default='time'),
            preserve_default=False,
        ),
    ]
