# Generated by Django 2.2.7 on 2020-05-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200511_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Summery',
            new_name='summery',
        ),
    ]
